### ISSUE TITLE
github icons are not displaying 

### ISSUE THREAD

**Issue by agarwalaman263** [fossasia/fossasia-gci#12]
In the cards used in the jury, upon hover, the icon for some of the social networking platforms are not visible. 
In the screenshot below, the code for GitHub profile is present but the icon is not visible
![screenshot 257](https://user-images.githubusercontent.com/16433241/37220503-dc2c908a-23ec-11e8-8a8f-71a749381dc4.png)

**Comment by mariobehling** [comment]
Closing in favor of https://github.com/fossasia/unesco.sciencehack.asia/issues/15
