### ISSUE TITLE
Add new Jury Members 

### ISSUE THREAD

**Issue by hpdang** [fossasia/fossasia-gci#6]
Please add two new Jury Member, next to Mario Behling on the website. 

1) Name: Vlado Koljibabic 
https://www.linkedin.com/in/kvlado80/

Photo: 
![vladokoljibabic](https://user-images.githubusercontent.com/1658742/37068437-ad02f984-21e9-11e8-800e-17a06c98c31d.jpg)

2) Name: Michael Christen
https://www.linkedin.com/in/orbiter/

Photo:
![michaelchristen](https://user-images.githubusercontent.com/1658742/37068483-e24173d2-21e9-11e8-87a0-934bba1a9bf4.jpeg)

**Comment by agarwalaman263** [comment]
The jury list is already modified
